# Generated by Django 5.1.2 on 2024-10-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_colour_size_remove_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colours',
            field=models.ManyToManyField(blank=True, to='api.colour'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, to='api.size'),
        ),
    ]
